---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: example assertion
      ansible.builtin.assert:
        that: true
# # given phase
# $ molecule create
# # when phase
# $ molecule converge
# # then phase
# $ molecule verify